"""progreso v1

Revision ID: 7833655356e2
Revises: 19b5a3ecf437
Create Date: 2025-10-10 12:09:16.119310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7833655356e2'
down_revision: Union[str, None] = '19b5a3ecf437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrocomida')
    op.drop_table('sesionentreno')
    op.alter_column('amistades', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('amistades', 'creada_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'amistades', 'usuarios', ['usuario_id_2'], ['id'])
    op.create_foreign_key(None, 'amistades', 'usuarios', ['usuario_id_1'], ['id'])
    op.alter_column('comida_imagenes', 'fecha_subida',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comida_imagenes', 'analisis_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('comida_imagenes', 'comentarios',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dietas', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('dietas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dietas', 'calorias_totales',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dietas', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dietas_generadas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dietas_generadas', 'datos_entrada',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dietas_generadas', 'dieta_json',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dietistas_favoritos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dietistas_favoritos', 'dietista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'rutina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'series',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'repeticiones',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'imagen_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'grupo_muscular',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ejercicios_rutina', 'equipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entrenadores_favoritos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entrenadores_favoritos', 'entrenador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entrenamientos', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('entrenamientos', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('entrenamientos', 'duracion_estim',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('entrenamientos', 'dificultad',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('exercise_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('exercise_sessions_id_seq'::regclass)"))
    op.alter_column('exercise_sessions', 'workout_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('exercise_sessions', 'descanso_minutos',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_exercise_sessions_ws_orden'), table_name='exercise_sessions')
    op.create_index(op.f('ix_exercise_sessions_workout_session_id'), 'exercise_sessions', ['workout_session_id'], unique=False)
    op.alter_column('formulario_cliente', 'deporte_especifico',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('formulario_cliente', 'semanas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formulario_cliente', 'aspectos_mejorar',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('formulario_cliente', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_formulario_cliente_id'), 'formulario_cliente', ['id'], unique=False)
    op.alter_column('formularios_dieta', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_dieta', 'altura',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_dieta', 'edad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_dieta', 'sexo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_dieta', 'objetivos',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('formularios_dieta', 'tipo_dieta',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_dieta', 'alergias',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_dieta', 'alimentos_no_deseados',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_dieta', 'tiempo_comidas',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_dieta', 'comidas_al_dia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_dieta', 'preferencias_alimentarias',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('formularios_dieta', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('formularios_mixto', sa.Column('semanas', sa.Integer(), nullable=False))
    op.alter_column('formularios_mixto', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_mixto', 'altura',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_mixto', 'edad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_mixto', 'sexo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'experiencia_entrenamiento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'tiempo_entrenamiento',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_mixto', 'preferencias',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('formularios_mixto', 'objetivos_entreno',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('formularios_mixto', 'nombre_deporte',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'aspectos_a_mejorar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'tipo_dieta',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'objetivos_dieta',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('formularios_mixto', 'alergias',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'alimentos_no_deseados',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'tiempo_comidas',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formularios_mixto', 'comidas_al_dia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('formularios_mixto', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('gimnasios', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gimnasios', 'direccion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gimnasios', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gimnasios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('infraestructura_gimnasio', 'fecha_subida',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('infraestructura_gimnasio_gimnasio_id_fkey'), 'infraestructura_gimnasio', type_='foreignkey')
    op.create_foreign_key(None, 'infraestructura_gimnasio', 'gimnasios', ['gimnasio_id'], ['id'])
    op.alter_column('planes', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('planes', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('planes_creado_por_fkey'), 'planes', type_='foreignkey')
    op.drop_constraint(op.f('fk_planes_formulario_dieta'), 'planes', type_='foreignkey')
    op.drop_constraint(op.f('planes_usuario_id_fkey'), 'planes', type_='foreignkey')
    op.create_foreign_key(None, 'planes', 'usuarios', ['creado_por'], ['id'])
    op.create_foreign_key(None, 'planes', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'planes', 'formularios_dieta', ['formulario_dieta_id'], ['id'])
    op.alter_column('planes_mixtos_generados', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('progreso', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progreso', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('progreso', 'progreso_detallado',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=False)
    op.drop_constraint(op.f('progreso_usuario_id_fkey'), 'progreso', type_='foreignkey')
    op.drop_constraint(op.f('progreso_plan_id_fkey'), 'progreso', type_='foreignkey')
    op.create_foreign_key(None, 'progreso', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'progreso', 'planes', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_progress_daily_user_date'), table_name='progress_daily')
    op.drop_constraint(op.f('uq_progress_daily_user_date'), 'progress_daily', type_='unique')
    op.alter_column('rest_periods', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('rest_periods', 'workout_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('rest_periods', 'exercise_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('rest_periods', 'tipo',
               existing_type=postgresql.ENUM('entre_series', 'entre_ejercicios', 'manual', name='rest_kind'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index(op.f('idx_rest_periods_ws'), table_name='rest_periods')
    op.create_index(op.f('ix_rest_periods_workout_session_id'), 'rest_periods', ['workout_session_id'], unique=False)
    op.alter_column('rutinas', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('rutinas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rutinas', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sesiones_entrenamiento', 'completado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sesiones_entrenamiento', 'comentarios',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('set_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('set_records', 'exercise_session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_set_records_exercise'), table_name='set_records')
    op.drop_constraint(op.f('set_records_exercise_session_id_set_index_key'), 'set_records', type_='unique')
    op.create_index(op.f('ix_set_records_exercise_session_id'), 'set_records', ['exercise_session_id'], unique=False)
    op.alter_column('usuario_planes', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuario_profesional', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_profesional', 'profesional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_profesional', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario_profesional', 'aceptado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'imagen_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.add_column('usuarios_amigos', sa.Column('usuario_id_1', sa.Integer(), nullable=True))
    op.add_column('usuarios_amigos', sa.Column('usuario_id_2', sa.Integer(), nullable=True))
    op.alter_column('usuarios_amigos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_amigos', 'amigo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_amigos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'usuarios_amigos', 'usuarios', ['usuario_id_1'], ['id'])
    op.create_foreign_key(None, 'usuarios_amigos', 'usuarios', ['usuario_id_2'], ['id'])
    op.alter_column('usuarios_gimnasios', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_gimnasios', 'gimnasio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_gimnasios', 'es_principal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios_gimnasios', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vinculaciones_profesionales', 'fecha_vinculacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('workout_sessions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.alter_column('workout_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('workout_sessions_id_seq'::regclass)"))
    op.alter_column('workout_sessions', 'fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('workout_sessions', 'descanso_total_min',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workout_sessions', 'estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'creada'::text"))
    op.drop_index(op.f('idx_workout_sessions_usuario_fecha'), table_name='workout_sessions')
    op.create_index(op.f('ix_workout_sessions_usuario_id'), 'workout_sessions', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'workout_sessions', 'planes', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_usuario_id'), table_name='workout_sessions')
    op.create_index(op.f('idx_workout_sessions_usuario_fecha'), 'workout_sessions', ['usuario_id', 'fecha'], unique=False)
    op.alter_column('workout_sessions', 'estado',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'creada'::text"))
    op.alter_column('workout_sessions', 'descanso_total_min',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('workout_sessions', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('workout_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('workout_sessions_id_seq'::regclass)"))
    op.drop_column('workout_sessions', 'plan_id')
    op.alter_column('vinculaciones_profesionales', 'fecha_vinculacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios_gimnasios', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios_gimnasios', 'es_principal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios_gimnasios', 'gimnasio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios_gimnasios', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'usuarios_amigos', type_='foreignkey')
    op.drop_constraint(None, 'usuarios_amigos', type_='foreignkey')
    op.alter_column('usuarios_amigos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios_amigos', 'amigo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios_amigos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('usuarios_amigos', 'usuario_id_2')
    op.drop_column('usuarios_amigos', 'usuario_id_1')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.alter_column('usuarios', 'imagen_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuario_profesional', 'aceptado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuario_profesional', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario_profesional', 'profesional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_profesional', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_planes', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_set_records_exercise_session_id'), table_name='set_records')
    op.create_unique_constraint(op.f('set_records_exercise_session_id_set_index_key'), 'set_records', ['exercise_session_id', 'set_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_set_records_exercise'), 'set_records', ['exercise_session_id', 'set_index'], unique=False)
    op.alter_column('set_records', 'exercise_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('set_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sesiones_entrenamiento', 'comentarios',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sesiones_entrenamiento', 'completado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rutinas', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rutinas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rutinas', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_rest_periods_workout_session_id'), table_name='rest_periods')
    op.create_index(op.f('idx_rest_periods_ws'), 'rest_periods', ['workout_session_id', 'started_at'], unique=False)
    op.alter_column('rest_periods', 'tipo',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('entre_series', 'entre_ejercicios', 'manual', name='rest_kind'),
               existing_nullable=False)
    op.alter_column('rest_periods', 'exercise_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('rest_periods', 'workout_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('rest_periods', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(op.f('uq_progress_daily_user_date'), 'progress_daily', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_progress_daily_user_date'), 'progress_daily', ['user_id', 'date'], unique=False)
    op.drop_constraint(None, 'progreso', type_='foreignkey')
    op.drop_constraint(None, 'progreso', type_='foreignkey')
    op.create_foreign_key(op.f('progreso_plan_id_fkey'), 'progreso', 'planes', ['plan_id'], ['id'])
    op.create_foreign_key(op.f('progreso_usuario_id_fkey'), 'progreso', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('progreso', 'progreso_detallado',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('progreso', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('progreso', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planes_mixtos_generados', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'planes', type_='foreignkey')
    op.drop_constraint(None, 'planes', type_='foreignkey')
    op.drop_constraint(None, 'planes', type_='foreignkey')
    op.create_foreign_key(op.f('planes_usuario_id_fkey'), 'planes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_planes_formulario_dieta'), 'planes', 'formularios_dieta', ['formulario_dieta_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('planes_creado_por_fkey'), 'planes', 'usuarios', ['creado_por'], ['id'], ondelete='SET NULL')
    op.alter_column('planes', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('planes', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'infraestructura_gimnasio', type_='foreignkey')
    op.create_foreign_key(op.f('infraestructura_gimnasio_gimnasio_id_fkey'), 'infraestructura_gimnasio', 'usuarios', ['gimnasio_id'], ['id'])
    op.alter_column('infraestructura_gimnasio', 'fecha_subida',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('gimnasios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gimnasios', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gimnasios', 'direccion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gimnasios', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('formularios_mixto', 'comidas_al_dia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_mixto', 'tiempo_comidas',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'alimentos_no_deseados',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'alergias',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'objetivos_dieta',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('formularios_mixto', 'tipo_dieta',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'aspectos_a_mejorar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'nombre_deporte',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'objetivos_entreno',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('formularios_mixto', 'preferencias',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('formularios_mixto', 'tiempo_entrenamiento',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_mixto', 'experiencia_entrenamiento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'sexo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_mixto', 'edad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_mixto', 'altura',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_mixto', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('formularios_mixto', 'semanas')
    op.alter_column('formularios_dieta', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('formularios_dieta', 'preferencias_alimentarias',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('formularios_dieta', 'comidas_al_dia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_dieta', 'tiempo_comidas',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_dieta', 'alimentos_no_deseados',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_dieta', 'alergias',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_dieta', 'tipo_dieta',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_dieta', 'objetivos',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('formularios_dieta', 'sexo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formularios_dieta', 'edad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_dieta', 'altura',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formularios_dieta', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_formulario_cliente_id'), table_name='formulario_cliente')
    op.alter_column('formulario_cliente', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('formulario_cliente', 'aspectos_mejorar',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('formulario_cliente', 'semanas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('formulario_cliente', 'deporte_especifico',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_exercise_sessions_workout_session_id'), table_name='exercise_sessions')
    op.create_index(op.f('idx_exercise_sessions_ws_orden'), 'exercise_sessions', ['workout_session_id', sa.literal_column('COALESCE(orden_real, orden_plan)')], unique=False)
    op.alter_column('exercise_sessions', 'descanso_minutos',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exercise_sessions', 'workout_session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('exercise_sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('exercise_sessions_id_seq'::regclass)"))
    op.alter_column('entrenamientos', 'dificultad',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('entrenamientos', 'duracion_estim',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entrenamientos', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('entrenamientos', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('entrenadores_favoritos', 'entrenador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entrenadores_favoritos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'equipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'grupo_muscular',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'imagen_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'repeticiones',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'series',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ejercicios_rutina', 'rutina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dietistas_favoritos', 'dietista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dietistas_favoritos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dietas_generadas', 'dieta_json',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dietas_generadas', 'datos_entrada',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dietas_generadas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dietas', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dietas', 'calorias_totales',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dietas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dietas', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('comida_imagenes', 'comentarios',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comida_imagenes', 'analisis_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('comida_imagenes', 'fecha_subida',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'amistades', type_='foreignkey')
    op.drop_constraint(None, 'amistades', type_='foreignkey')
    op.alter_column('amistades', 'creada_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('amistades', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('sesionentreno',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sesionentreno_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entrenamiento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_programada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('peso_usado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('series', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repeticiones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descanso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso_corporal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entrenamiento_id'], ['entrenamientos.id'], name=op.f('sesionentreno_entrenamiento_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('sesionentreno_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sesionentreno_pkey'))
    )
    op.create_table('registrocomida',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('registrocomida_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_comida', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ingredientes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imagen_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('registrocomida_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('registrocomida_pkey'))
    )
    # ### end Alembic commands ###
